replicaCount: 1
image:
  repository: ghcr.io/acdh-oeaw/recogito-studio/recogito-studio
  tag: "$tag"
  pullPolicy: Always
  secrets: []
extraLabels:
  "ID": "22985"
gitlab:
  app: "recogito-studio-prod"
  envURL: "git://github.com/acdh-oeaw/recogito-studio.git"
service:
  enabled: true
  name: "web"
  url: "https://recogito-studio.acdh-dev.oeaw.ac.at"
  additionalHosts:
    - recogito-studio-prod-main.acdh-dev.oeaw.ac.at
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000
ingress:
  enabled: false
  path: "/"
  annotations:
    kubernetes.io/ingressClassName: "nginx"
livenessProbe:
  path: "/"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"
startupProbe:
  path: "/"
  initialDelaySeconds: 30
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"